#=================Property Configuration===========================
global  variation_dic_happy_flow, variation_dic_fast_flow,variation_dic_fail_3cycles,variation_dic_fail_cycle1_pass_cycle2,topic_strand_dic
variation_dic_happy_flow = {
'avatar_editor':'complete',
'avatar_editor_initial':'complete',
'backpack_gathering':'complete',
'blend_new_words':'complete',
'collections_explore_mode':'complete',
'collections_my_books':'complete',
'direct_instruction':'complete',
'direct_instruction_wp':'complete',
'ebook_1st_read':'full_read',
'ebook_2nd_read':'complete',
'end_of_topic':'complete',
'end_of_series':'complete',
'letter_hunt':'all_correct',
'letter_name_challenge':'all_correct',
'letter_name_id':'all_accurate',
'letter_sound_challenge':'all_correct',
'letter_sound_id':'all_accurate',
'letter_sound_matching':'all_rounds_complete',
'letter_zone_transition':'complete',
'listening_zone_transition':'complete',
'main_hall_outro':'complete',
'meaning_machine':'all_correct',
'mix_match_sounds':'all_correct',
'mix_match_words':'all_correct',
'pa_rhyme':'all_correct',
'pa_syllable_counting':'all_correct',
'pa_syllable_blending':'all_correct',
'pa_warm_up':'all_correct',
'pa_warm_up_al':'all_correct',
'read_a_story':'complete',
'read_think':'all_correct',
'reading_zone_transition':'complete',
'screener':'all_sections_complete',
'sentence_fill_in':'all_correct',
'series_assessment':'all_sections_all_incorrect',
'series_assessment_end_period':'no_data',
'sight_word_check_up':'random_missed',
'sight_word_hunt':'all_correct',
'sight_word_intro':'complete',
'sound_zone_di':'complete',
'sound_zone_transition':'complete',
'spelling_challenge':'all_correct',
'spelling_check_up':'all_correct',
'spelling_clinic':'complete',
'spelling_zone_transition':'complete',
'spin_the_wheel':'all_correct',
'teacher_greeting':'complete',
'word_building':'all_correct',
'word_challenge':'all_correct',
'word_challenge_sw':'all_correct',
'word_changer':'all_correct',
'word_id':'all_accurate',
'word_id_sw':'all_accurate',
'word_meaning_match':'all_correct',
'word_splitter':'all_correct',
'word_zone_di':'complete',
'word_zone_transition':'complete',
'':'',
}
variation_dic_fast_flow = {
'avatar_editor':'complete',
'avatar_editor_initial':'complete',
'backpack_gathering':'complete',
'blend_new_words':'complete',
'collections_explore_mode':'complete',
'collections_my_books':'complete',
'direct_instruction':'complete',
'direct_instruction_wp':'complete',
'ebook_1st_read':'full_read',
'ebook_2nd_read':'complete',
'end_of_topic':'complete',
'end_of_series':'complete',
'letter_hunt':'all_correct',
'letter_name_challenge':'all_correct',
'letter_name_id':'all_accurate',
'letter_sound_challenge':'all_correct',
'letter_sound_id':'all_accurate',
'letter_sound_matching':'all_rounds_complete',
'letter_zone_transition':'complete',
'listening_zone_transition':'complete',
'main_hall_outro':'complete',
'meaning_machine':'all_correct',
'mix_match_sounds':'all_correct',
'mix_match_words':'all_correct',
'pa_rhyme':'all_correct',
'pa_syllable_counting':'all_correct',
'pa_syllable_blending':'all_correct',
'pa_warm_up':'all_correct',
'pa_warm_up_al':'all_correct',
'read_a_story':'complete',
'read_think':'all_correct',
'reading_zone_transition':'complete',
'screener':'all_sections_complete',
'sentence_fill_in':'all_correct',
'series_assessment':'all_sections_all_correct',       #
'series_assessment_end_period':'no_data',
'sight_word_check_up':'all_correct',
'sight_word_hunt':'all_correct',
'sight_word_intro':'complete',
'sound_zone_di':'complete',
'sound_zone_transition':'complete',
'spelling_challenge':'all_correct',
'spelling_check_up':'all_correct',
'spelling_clinic':'complete',
'spelling_zone_transition':'complete',
'spin_the_wheel':'all_correct',
'teacher_greeting':'complete',
'word_building':'all_correct',
'word_challenge':'all_correct',
'word_challenge_sw':'all_correct',
'word_changer':'all_correct',
'word_id':'all_accurate',
'word_id_sw':'all_accurate',
'word_meaning_match':'all_correct',
'word_splitter':'all_correct',
'word_zone_di':'complete',
'word_zone_transition':'complete',
'':'',
}


variation_dic_fail_3cycles = {
'avatar_editor':'complete',
'avatar_editor_initial':'complete',
'backpack_gathering':'complete',
'blend_new_words':'complete',
'collections_explore_mode':'complete',
'collections_my_books':'complete',
'direct_instruction':'complete',
'direct_instruction_wp':'complete',
'ebook_1st_read':'full_read',
'ebook_2nd_read':'complete',
'end_of_topic':'complete',
'end_of_series':'complete',
'letter_hunt':'all_correct',
'letter_name_challenge':'all_correct',
'letter_name_id':'all_accurate',
'letter_sound_challenge':'all_correct',
'letter_sound_id':'all_accurate',
'letter_sound_matching':'all_rounds_complete',
'letter_zone_transition':'complete',
'listening_zone_transition':'complete',
'main_hall_outro':'complete',
'meaning_machine':'all_correct',
'mix_match_sounds':'all_correct',
'mix_match_words':'all_correct',
'pa_rhyme':'all_correct',
'pa_syllable_counting':'all_correct',
'pa_syllable_blending':'all_correct',
'pa_warm_up':'all_correct',
'pa_warm_up_al':'all_correct',
'read_a_story':'complete',
'read_think':'all_correct',
'reading_zone_transition':'complete',
'screener':'all_sections_complete',
'sentence_fill_in':'all_correct',
'series_assessment':'all_sections_all_incorrect',
'series_assessment_end_period':'no_data',
'sight_word_check_up':'random_missed',
'sight_word_hunt':'all_correct',
'sight_word_intro':'complete',
'sound_zone_di':'complete',
'sound_zone_transition':'complete',
'spelling_challenge':'all_correct',
'spelling_check_up':'all_correct',
'spelling_clinic':'complete',
'spelling_zone_transition':'complete',
'spin_the_wheel':'all_correct',
'teacher_greeting':'complete',
'word_building':'all_correct',
'word_challenge':'all_correct',
'word_challenge_sw':'all_correct',
'word_changer':'all_correct',
'word_id':'all_inaccurate',
'word_id_sw':'all_inaccurate',
'word_meaning_match':'all_correct',
'word_splitter':'all_correct',
'word_zone_di':'complete',
'word_zone_transition':'complete',
'':'',
}
variation_dic_unhappy_ = {
'avatar_editor':'complete',
'avatar_editor_initial':'complete',
'backpack_gathering':'complete',
'blend_new_words':'complete',
'collections_explore_mode':'complete',
'collections_my_books':'complete',
'direct_instruction':'complete',
'direct_instruction_wp':'complete',
'ebook_1st_read':'full_read',              
'ebook_2nd_read':'complete',               
'end_of_topic':'complete',
'end_of_series':'complete',
'letter_hunt':'all_correct',               
'letter_name_challenge':'all_incorrect',     #
'letter_name_id':'all_inaccurate',           #
'letter_sound_challenge':'all_incorrect',    #
'letter_sound_id':'all_inaccurate',          #
'letter_sound_matching':'fail_round_2',      #
'letter_zone_transition':'complete',
'listening_zone_transition':'complete',
'main_hall_outro':'complete',
'meaning_machine':'all_correct',           
'mix_match_sounds':'all_correct',          
'mix_match_words':'all_correct',           
'pa_rhyme':'all_incorrect',                  #
'pa_syllable_counting':'all_incorrect',      #
'pa_syllable_blending':'all_incorrect',      #      
'pa_warm_up':'some_incorrect',               #
'pa_warm_up_al':'some_incorrect',            #
'read_a_story':'complete',
'read_think':'all_incorrect',                #
'reading_zone_transition':'complete',
'screener':'all_sections_complete',
'sentence_fill_in':'all_correct',
'series_assessment':'all_sections_all_correct',  #
'series_assessment_end_period':'no_data',
'sight_word_check_up':'random_missed',         #
'sight_word_hunt':'random',                    #
'sight_word_intro':'complete',
'sound_zone_di':'complete',
'sound_zone_transition':'complete',
'spelling_challenge':'all_incorrect',         #
'spelling_check_up':'all_incorrect',   #
'spelling_clinic':'complete',
'spelling_zone_transition':'complete',
'spin_the_wheel':'some_correct',            #
'teacher_greeting':'complete',
'word_building':'all_incorrect',           #
'word_challenge':'all_incorrect',        #
'word_challenge_sw':'all_incorrect',          #
'word_changer':'all_incorrect',              #
'word_id':'all_inaccurate',                 #
'word_id_sw':'all_inaccurate',               #
'word_meaning_match':'all_incorrect',         #
'word_splitter':'all_incorrect',           #
'word_zone_di':'complete',
'word_zone_transition':'complete',
'':'',
}
variation_dic_fail_cycle1_pass_cycle2 = {
'avatar_editor':'complete',
'avatar_editor_initial':'complete',
'backpack_gathering':'complete',
'blend_new_words':'complete',
'collections_explore_mode':'complete',
'collections_my_books':'complete',
'direct_instruction':'complete',
'direct_instruction_wp':'complete',
'ebook_1st_read':'full_read',
'ebook_2nd_read':'complete',
'end_of_topic':'complete',
'end_of_series':'complete',
'letter_hunt':'all_correct',
'letter_name_challenge':'all_correct',
'letter_name_id':'all_accurate',
'letter_sound_challenge':'all_correct',
'letter_sound_id':'all_accurate',
'letter_sound_matching':'all_rounds_complete',
'letter_zone_transition':'complete',
'listening_zone_transition':'complete',
'main_hall_outro':'complete',
'meaning_machine':'all_correct',
'mix_match_sounds':'all_correct',
'mix_match_words':'all_correct',
'pa_rhyme':'all_correct',
'pa_syllable_counting':'all_correct',
'pa_syllable_blending':'all_correct',
'pa_warm_up':'all_correct',
'pa_warm_up_al':'all_correct',
'read_a_story':'complete',
'read_think':'all_correct',
'reading_zone_transition':'complete',
'screener':'all_sections_complete',
'sentence_fill_in':'all_correct',
'series_assessment':'all_sections_all_incorrect',
'series_assessment_end_period':'no_data',
'sight_word_check_up':'random_missed',
'sight_word_hunt':'all_correct',
'sight_word_intro':'complete',
'sound_zone_di':'complete',
'sound_zone_transition':'complete',
'spelling_challenge':'all_correct',
'spelling_check_up':'all_correct',
'spelling_clinic':'complete',
'spelling_zone_transition':'complete',
'spin_the_wheel':'all_correct',
'teacher_greeting':'complete',
'word_building':'all_correct',
'word_challenge':'all_correct',
'word_challenge_sw':'all_correct',
'word_changer':'all_correct',
'word_id':['all_inaccurate','all_accurate'],
'word_id_sw':['all_inaccurate','all_accurate'],
'word_meaning_match':'all_correct',
'word_splitter':'all_correct',
'word_zone_di':'complete',
'word_zone_transition':'complete',
'':'',
}

topic_strand_dic = {
"series_01": "series_assessment",
"series_01_topic_01": "alphabet_strand_unit1_2",
"series_01_topic_02": "alphabet_strand_unit1_2",
"series_01_topic_03": "alphabet_strand_unit1_2",
"series_01_topic_04": "alphabet_strand_unit1_2",
"series_01_topic_05": "success_strand",
"series_02": "series_assessment",
"series_02_topic_01": "alphabet_strand_unit1_2",
"series_02_topic_02": "alphabet_strand_unit1_2",
"series_02_topic_03": "alphabet_strand_unit1_2",
"series_02_topic_04": "alphabet_strand_unit1_2",
"series_02_topic_05": "success_strand",
"series_03": "series_assessment",
"series_03_topic_01": "alphabet_strand_unit1_2",
"series_03_topic_02": "alphabet_strand_unit1_2",
"series_03_topic_03": "alphabet_strand_unit1_2",
"series_03_topic_04": "alphabet_strand_unit1_2",
"series_03_topic_05": "alphabet_strand_unit1_2",
"series_03_topic_06": "success_strand",
"series_04": "series_assessment",
"series_04_topic_01": "alphabet_strand_unit1_2",
"series_04_topic_02": "alphabet_strand_unit1_2",
"series_04_topic_03": "alphabet_strand_unit1_2",
"series_04_topic_04": "alphabet_strand_unit1_2",
"series_04_topic_05": "success_strand",
"series_05": "series_assessment",
"series_05_topic_01": "alphabet_strand_unit1_2",
"series_05_topic_02": "alphabet_strand_unit1_2",
"series_05_topic_03": "alphabet_strand_unit1_2",
"series_05_topic_04": "alphabet_strand_unit1_2",
"series_05_topic_05": "success_strand",
"series_06": "series_assessment",
"series_06_topic_01": "alphabet_strand_unit1_2",
"series_06_topic_02": "alphabet_strand_unit1_2",
"series_06_topic_03": "alphabet_strand_unit1_2",
"series_06_topic_04": "alphabet_strand_unit1_2",
"series_06_topic_05": "alphabet_strand_unit1_2",
"series_06_topic_06": "success_strand",
"series_07": "series_assessment",
"series_07_topic_01": "alphabet_strand_unit3",
"series_07_topic_02": "alphabet_strand_unit3",
"series_07_topic_03": "alphabet_strand_unit3",
"series_07_topic_04": "alphabet_strand_unit3",
"series_07_topic_05": "success_strand",
"series_08": "series_assessment",
"series_08_topic_01": "alphabet_strand_unit3",
"series_08_topic_02": "alphabet_strand_unit3",
"series_08_topic_03": "alphabet_strand_unit3",
"series_08_topic_04": "alphabet_strand_unit3",
"series_08_topic_05": "success_strand",
"series_09": "series_assessment",
"series_09_topic_01": "alphabet_strand_unit3",
"series_09_topic_02": "alphabet_strand_unit3",
"series_09_topic_03": "alphabet_strand_unit3",
"series_09_topic_04": "alphabet_strand_unit3",
"series_09_topic_05": "alphabet_strand_unit3",
"series_09_topic_06": "sight_words_strand",
"series_09_topic_07": "success_strand",
"series_10": "series_assessment",
"series_10_topic_01": "alphabet_strand_unit3",
"series_10_topic_02": "alphabet_strand_unit3",
"series_10_topic_03": "alphabet_strand_unit3",
"series_10_topic_04": "alphabet_strand_unit3",
"series_10_topic_05": "sight_words_strand",
"series_10_topic_06": "success_strand",
"series_11": "series_assessment",
"series_11_topic_01": "alphabet_strand_unit3",
"series_11_topic_02": "alphabet_strand_unit3",
"series_11_topic_03": "alphabet_strand_unit3",
"series_11_topic_04": "alphabet_strand_unit3",
"series_11_topic_05": "sight_words_strand",
"series_11_topic_06": "success_strand",
"series_12": "series_assessment",
"series_12_topic_01": "alphabet_strand_unit3",
"series_12_topic_02": "alphabet_strand_unit3",
"series_12_topic_03": "alphabet_strand_unit3",
"series_12_topic_04": "alphabet_strand_unit3",
"series_12_topic_05": "alphabet_strand_unit3",
"series_12_topic_06": "sight_words_strand",
"series_12_topic_07": "success_strand",
"series_13": "series_assessment",
"series_13_topic_01": "code_strand_unit4",
"series_13_topic_02": "code_strand_unit4",
"series_13_topic_03": "code_strand_unit4",
"series_13_topic_04": "code_strand_unit4",
"series_13_topic_05": "word_play_strand",
"series_13_topic_06": "sight_words_strand",
"series_13_topic_07": "success_strand",
"series_14": "series_assessment",
"series_14_topic_01": "code_strand_unit4",
"series_14_topic_02": "code_strand_unit4",
"series_14_topic_03": "code_strand_unit4",
"series_14_topic_04": "code_strand_unit4",
"series_14_topic_05": "word_play_strand",
"series_14_topic_06": "sight_words_strand",
"series_14_topic_07": "success_strand",
"series_15": "series_assessment",
"series_15_topic_01": "code_strand_unit4",
"series_15_topic_02": "code_strand_unit4",
"series_15_topic_03": "code_strand_unit4",
"series_15_topic_04": "sight_words_strand",
"series_15_topic_05": "success_strand",
"series_16": "series_assessment",
"series_16_topic_01": "code_strand_unit4",
"series_16_topic_02": "code_strand_unit4",
"series_16_topic_03": "code_strand_unit4",
"series_16_topic_04": "word_play_strand",
"series_16_topic_05": "sight_words_strand",
"series_16_topic_06": "success_strand",
"series_17": "series_assessment",
"series_17_topic_01": "code_strand_unit4",
"series_17_topic_02": "code_strand_unit4",
"series_17_topic_03": "code_strand_unit4",
"series_17_topic_04": "sight_words_strand",
"series_17_topic_05": "success_strand",
"series_18": "series_assessment",
"series_18_topic_01": "code_strand_unit4",
"series_18_topic_02": "code_strand_unit4",
"series_18_topic_03": "code_strand_unit4",
"series_18_topic_04": "sight_words_strand",
"series_18_topic_05": "success_strand",
"series_19": "series_assessment",
"series_19_topic_01": "code_strand_unit5_11",
"series_19_topic_02": "code_strand_unit5_11",
"series_19_topic_03": "code_strand_unit5_11",
"series_19_topic_04": "code_strand_unit5_11",
"series_19_topic_05": "sight_words_strand",
"series_19_topic_06": "success_strand",
"series_20": "series_assessment",
"series_20_topic_01": "code_strand_unit5_11",
"series_20_topic_02": "code_strand_unit5_11",
"series_20_topic_03": "code_strand_unit5_11",
"series_20_topic_04": "word_play_strand",
"series_20_topic_05": "word_play_strand",
"series_20_topic_06": "sight_words_strand",
"series_20_topic_07": "success_strand",
"series_21": "series_assessment",
"series_21_topic_01": "code_strand_unit5_11",
"series_21_topic_02": "code_strand_unit5_11",
"series_21_topic_03": "code_strand_unit5_11",
"series_21_topic_04": "code_strand_unit5_11",
"series_21_topic_05": "sight_words_strand",
"series_21_topic_06": "success_strand",
"series_22": "series_assessment",
"series_22_topic_01": "code_strand_unit5_11",
"series_22_topic_02": "code_strand_unit5_11",
"series_22_topic_03": "code_strand_unit5_11",
"series_22_topic_04": "code_strand_unit5_11",
"series_22_topic_05": "sight_words_strand",
"series_22_topic_06": "success_strand",
"series_23": "series_assessment",
"series_23_topic_01": "code_strand_unit5_11",
"series_23_topic_02": "code_strand_unit5_11",
"series_23_topic_03": "code_strand_unit5_11",
"series_23_topic_04": "word_play_strand",
"series_23_topic_05": "word_play_strand",
"series_23_topic_06": "sight_words_strand",
"series_23_topic_07": "success_strand",
"series_24": "series_assessment",
"series_24_topic_01": "word_play_strand",
"series_24_topic_02": "code_strand_unit5_11",
"series_24_topic_03": "code_strand_unit5_11",
"series_24_topic_04": "code_strand_unit5_11",
"series_24_topic_05": "code_strand_unit5_11",
"series_24_topic_06": "sight_words_strand",
"series_24_topic_07": "success_strand",
"series_25": "series_assessment",
"series_25_topic_01": "code_strand_unit5_11",
"series_25_topic_02": "code_strand_unit5_11",
"series_25_topic_03": "code_strand_unit5_11",
"series_25_topic_04": "word_play_strand",
"series_25_topic_05": "word_play_strand",
"series_25_topic_06": "sight_words_strand",
"series_25_topic_07": "success_strand",
"series_26": "series_assessment",
"series_26_topic_01": "code_strand_unit5_11",
"series_26_topic_02": "code_strand_unit5_11",
"series_26_topic_03": "code_strand_unit5_11",
"series_26_topic_04": "word_play_strand",
"series_26_topic_05": "sight_words_strand",
"series_26_topic_06": "success_strand",
"series_27": "series_assessment",
"series_27_topic_01": "code_strand_unit5_11",
"series_27_topic_02": "word_play_strand",
"series_27_topic_03": "word_play_strand",
"series_27_topic_04": "sight_words_strand",
"series_27_topic_05": "success_strand",
"series_28": "series_assessment",
"series_28_topic_01": "code_strand_unit5_11",
"series_28_topic_02": "code_strand_unit5_11",
"series_28_topic_03": "code_strand_unit5_11",
"series_28_topic_04": "code_strand_unit5_11",
"series_28_topic_05": "sight_words_strand",
"series_28_topic_06": "success_strand",
"series_29": "series_assessment",
"series_29_topic_01": "code_strand_unit5_11",
"series_29_topic_02": "code_strand_unit5_11",
"series_29_topic_03": "word_play_strand",
"series_29_topic_04": "word_play_strand",
"series_29_topic_05": "sight_words_strand",
"series_29_topic_06": "success_strand",
"series_30": "series_assessment",
"series_30_topic_01": "code_strand_unit5_11",
"series_30_topic_02": "word_play_strand",
"series_30_topic_03": "word_play_strand",
"series_30_topic_04": "word_play_strand",
"series_30_topic_05": "sight_words_strand",
"series_30_topic_06": "success_strand",
"series_31": "series_assessment",
"series_31_topic_01": "code_strand_unit5_11",
"series_31_topic_02": "code_strand_unit5_11",
"series_31_topic_03": "code_strand_unit5_11",
"series_31_topic_04": "code_strand_unit5_11",
"series_31_topic_05": "sight_words_strand",
"series_31_topic_06": "success_strand",
"series_32": "series_assessment",
"series_32_topic_01": "code_strand_unit5_11",
"series_32_topic_02": "code_strand_unit5_11",
"series_32_topic_03": "code_strand_unit5_11",
"series_32_topic_04": "code_strand_unit5_11",
"series_32_topic_05": "word_play_strand",
"series_32_topic_06": "sight_words_strand",
"series_32_topic_07": "success_strand",
"series_33": "series_assessment",
"series_33_topic_01": "code_strand_unit5_11",
"series_33_topic_02": "code_strand_unit5_11",
"series_33_topic_03": "code_strand_unit5_11",
"series_33_topic_04": "code_strand_unit5_11",
"series_33_topic_05": "sight_words_strand",
"series_33_topic_06": "success_strand",
"series_34": "series_assessment",
"series_34_topic_01": "word_play_strand",
"series_34_topic_02": "word_play_strand",
"series_34_topic_03": "word_play_strand",
"series_34_topic_04": "word_play_strand",
"series_34_topic_05": "sight_words_strand",
"series_34_topic_06": "success_strand",
"series_35": "series_assessment",
"series_35_topic_01": "code_strand_unit5_11",
"series_35_topic_02": "word_play_strand",
"series_35_topic_03": "code_strand_unit5_11",
"series_35_topic_04": "sight_words_strand",
"series_35_topic_05": "success_strand",
"series_36": "series_assessment",
"series_36_topic_01": "code_strand_unit5_11",
"series_36_topic_02": "code_strand_unit5_11",
"series_36_topic_03": "code_strand_unit5_11",
"series_36_topic_04": "code_strand_unit5_11",
"series_36_topic_05": "code_strand_unit5_11",
"series_36_topic_06": "sight_words_strand",
"series_36_topic_07": "success_strand",
"series_37": "series_assessment",
"series_37_topic_01": "code_strand_unit12",
"series_37_topic_02": "code_strand_unit12",
"series_37_topic_03": "code_strand_unit12",
"series_37_topic_04": "code_strand_unit12",
"series_37_topic_05": "code_strand_unit12",
"series_37_topic_06": "sight_words_strand",
"series_37_topic_07": "success_strand",
"series_38": "series_assessment",
"series_38_topic_01": "code_strand_unit12",
"series_38_topic_02": "code_strand_unit12",
"series_38_topic_03": "code_strand_unit12",
"series_38_topic_04": "code_strand_unit12",
"series_38_topic_05": "code_strand_unit12",
"series_38_topic_06": "sight_words_strand",
"series_38_topic_07": "success_strand",
"series_39": "series_assessment",
"series_39_topic_01": "word_play_strand",
"series_39_topic_02": "word_play_strand",
"series_39_topic_03": "word_play_strand",
"series_39_topic_04": "sight_words_strand",
"series_39_topic_05": "success_strand",
"series_40": "series_assessment",
"series_40_topic_01": "word_play_strand",
"series_40_topic_02": "word_play_strand",
"series_40_topic_03": "word_play_strand",
"series_40_topic_04": "word_play_strand",
"series_40_topic_05": "sight_words_strand",
"series_40_topic_06": "success_strand",
"series_41": "series_assessment",
"series_41_topic_01": "code_strand_unit12",
"series_41_topic_02": "word_play_strand",
"series_41_topic_03": "word_play_strand",
"series_41_topic_04": "sight_words_strand",
"series_41_topic_05": "success_strand",
"series_42": "series_assessment",
"series_42_topic_01": "code_strand_unit12",
"series_42_topic_02": "code_strand_unit12",
"series_42_topic_03": "code_strand_unit12",
"series_42_topic_04": "word_play_strand",
"series_42_topic_05": "sight_words_strand",
"series_42_topic_06": "success_strand",
"series_43": "series_assessment",
"series_43_topic_01": "word_play_strand",
"series_43_topic_02": "word_play_strand",
"series_43_topic_03": "word_play_strand",
"series_43_topic_04": "word_play_strand",
"series_43_topic_05": "word_play_strand",
"series_43_topic_06": "sight_words_strand",
"series_43_topic_07": "success_strand",
"series_44": "series_assessment",
"series_44_topic_01": "code_strand_unit12",
"series_44_topic_02": "word_play_strand",
"series_44_topic_03": "word_play_strand",
"series_44_topic_04": "word_play_strand",
"series_44_topic_05": "word_play_strand",
"series_44_topic_06": "sight_words_strand",
"series_44_topic_07": "success_strand",
"series_45": "series_assessment",
"series_45_topic_01": "code_strand_unit12",
"series_45_topic_02": "code_strand_unit12",
"series_45_topic_03": "word_play_strand",
"series_45_topic_04": "word_play_strand",
"series_45_topic_05": "word_play_strand",
"series_45_topic_06": "sight_words_strand",
"series_45_topic_07": "success_strand",
"series_46": "series_assessment",
"series_46_topic_01": "code_strand_unit12",
"series_46_topic_02": "code_strand_unit12",
"series_46_topic_03": "code_strand_unit12",
"series_46_topic_04": "word_play_strand",
"series_46_topic_05": "word_play_strand",
"series_46_topic_06": "sight_words_strand",
"series_46_topic_07": "success_strand",
"series_47": "series_assessment",
"series_47_topic_01": "code_strand_unit12",
"series_47_topic_02": "code_strand_unit12",
"series_47_topic_03": "word_play_strand",
"series_47_topic_04": "word_play_strand",
"series_47_topic_05": "sight_words_strand",
"series_47_topic_06": "success_strand",
"series_48": "series_assessment",
"series_48_topic_01": "code_strand_unit12",
"series_48_topic_02": "word_play_strand",
"series_48_topic_03": "word_play_strand",
"series_48_topic_04": "word_play_strand",
"series_48_topic_05": "sight_words_strand",
"series_48_topic_06": "success_strand",
"series_49": "series_assessment",
"series_49_topic_01": "code_strand_unit12",
"series_49_topic_02": "code_strand_unit12",
"series_49_topic_03": "code_strand_unit12",
"series_49_topic_04": "code_strand_unit12",
"series_49_topic_05": "code_strand_unit12",
"series_49_topic_06": "sight_words_strand",
"series_49_topic_07": "success_strand",
"series_50": "series_assessment",
"series_50_topic_01": "code_strand_unit12",
"series_50_topic_02": "code_strand_unit12",
"series_50_topic_03": "code_strand_unit12",
"series_50_topic_04": "word_play_strand",
"series_50_topic_05": "sight_words_strand",
"series_50_topic_06": "success_strand",
"series_51": "series_assessment",
"series_51_topic_01": "code_strand_unit12",
"series_51_topic_02": "code_strand_unit12",
"series_51_topic_03": "word_play_strand",
"series_51_topic_04": "word_play_strand",
"series_51_topic_05": "sight_words_strand",
"series_51_topic_06": "success_strand",
"series_52": "",
}